System Variable:
  Name:               "*PRODREL"
  Description:        "Current LANSA release level"
  Derivation:         Static
  Data Type:          Numeric
  Length:             3
  Decimals:           1
  Program Type:       3GL Program
  Program Name:       M@SYSVAR
